### ISSUE TITLE
RFC configuration directly in app.php

### ISSUE THREAD

**Issue by cake17** [cakephp-fr/cookie-warning#3]
I'm wondering if we could avoid the config file `cookie_warning` and just place the config in app.php.
I did that for the [Recaptcha plugin](https://github.com/cakephp-fr/recaptcha).

What do you think about it ?

**Comment by cyberbobjr** [comment]
Why not, what's the benefit ?

**Comment by cake17** [comment]
Just to simplify the configuration, no need to integrate a new file...
